name: Laravel CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP Dependencies
        run: composer install
      - name: Run Tests
        run: php artisan test
